on:
  push:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      # 4.2.2
      - name: 'Checkout'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 

      - run: |
          ls
          
      - name: Set up Docker Buildx
      # 3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Should Deploy to GHCR?'
        id: should_deploy
        run: |
          DEPLOY=false
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            DEPLOY=true
          fi
          echo "should_deploy=${DEPLOY}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ steps.should_deploy.outputs.should_deploy }}
          tags: ghcr.io/cloudcampla/microbootcamp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max