on:
  push:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 

      - run: ls

      - name: 'Build Container'
        run: |
          docker build -t ghcr.io/cloudcamp/microbootcamp:latest .

      - name: 'Login to GHCR'
        env:
          CR_PAT: ${{ github.token }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u daviddager --password-stdin

      - name: 'Push image to GHCR'
        run: |
          docker push ghcr.io/cloudcamp/microbootcamp:latest